### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by icantdothisbro** [zhanghang1989/detectron2-ResNeSt#14]
cfg.merge_from_file("faster_cascade_rcnn_ResNeSt_50_FPN_syncbn_range-scale-1x.yaml")
running this giver key error.
The error thrown exactly is :
KeyError: 'Non-existent config key: MODEL.RESNETS.RADIX'

**Comment by chongruo** [comment]
Did you use the current repo?

The radix is defined here. https://github.com/zhanghang1989/detectron2-ResNeSt/blob/64c20499649aaea0c31928cfd7dbc1bd42b02e57/detectron2/config/defaults.py#L496

**Comment by icantdothisbro** [comment]
Yes , I am using the path from the current repo only.
This is what i write :
cfg.merge_from_file("./detectron2-ResNeSt/configs/COCO-Detection/faster_cascade_rcnn_ResNeSt_200_FPN_syncbn_range-scale_1x.yaml")

After running this , the error is thrown.

**Comment by chongruo** [comment]
should use the current codebase. We define several hyper-parameters, including radix.

**Comment by icantdothisbro** [comment]
@chongruo  yeah! It worked. Was probably using some other version , I added manually
" _C.MODEL.RESNETS.RADIX = 1" line in the file that you mentioned and did a rebuild and it worked.
Thanks
